### ISSUE TITLE
[Campaign] Overflowing campaign name creates unnecessary white space on the right side of the page

### ISSUE THREAD

**Issue by mop13** [sleepbusorg/sleepbus.org#110]
### Title
[Campaign] Overflowing campaign name creates unnecessary white space on the right side of the page
### Platform / OS 
Windows 10
### Browser
Chrome
### Description
If user created a very long campaign name (max 80 char) the name will overflow and create unnecessary space on the right side of the page
### Steps to Reproduce

1. Create a new campaign with very long campaign name
2. Visit the campaign page after successfully creating the campaign. Sample page --https://dev.sleepbus.org/campaign/test-lenght-wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
3. Notice that overflowing campaign name and page can be move to the right side

### Expected Behavior 
Make necessary cut-off for wrapping the text so that overflow will not be an issue or limit the number of characters that can be inputted on the text field.
### Additional Info
![image](https://user-images.githubusercontent.com/30305608/28867325-49e4a992-77a8-11e7-94c6-da92eb62f76d.png)
![image](https://user-images.githubusercontent.com/30305608/28866800-9cd6f72e-77a6-11e7-9580-48d31aa11edc.png)
Branch: 54789c348427efcfa22edd86964eb9b398ea178e
dev Build: https://circleci.com/gh/sleepbusorg/sleepbus.org/169

**Comment by mop13** [comment]
creating an update and comment with too much characters also makes unnecessary white space on the right side of the page. Probably best to limit the number of characters and put a proper border where text should begin to wrap.

https://dev.sleepbus.org/campaign/test-campaign-a-2

**Comment by leonstafford** [comment]
won't fix
