### ISSUE TITLE
[Profile] Overflowing profile name creates unnecessary white space

### ISSUE THREAD

**Issue by mop13** [sleepbusorg/sleepbus.org#111]
### Title
[Profile] Overflowing profile name creates unnecessary white space
### Platform / OS 
Windows 10
### Browser
Chrome
### Description
Creating a lengthy profile name will display an overflowing text and unnecessary white space
### Steps to Reproduce

1. Log in to your account
2. Edit your profile name with a lengthy text and save
3. Notice the overflowing text and white space at the right side of the page

### Expected Behavior 
No overflowing text and unnecessary white space due to lengthy profile names. Name should be wrap or make a maximum character input for names.
### Additional Info
![image](https://user-images.githubusercontent.com/30305608/28905768-5e7b8ac2-7845-11e7-9144-6d996d50e176.png)
Branch: aa964f7da50b7866b12349886397c6c413a4c3a3
dev Build: https://circleci.com/gh/sleepbusorg/sleepbus.org/170

**Comment by mop13** [comment]
happens on

- [ ] my profile page

- [ ] my donations page

**Comment by leonstafford** [comment]
won't fix
