### ISSUE TITLE
[FAQ] Webpage seems focusing on wrong section when a section link is clicked

### ISSUE THREAD

**Issue by mop13** [sleepbusorg/sleepbus.org#118]
### Title
[FAQ] Webpage seems focusing on wrong section when a section link is clicked
### Platform / OS 
Windows 10
### Browser
Microsoft Edge
### Description
The webpage jumps a bit high and the header covers up the correct section title that user intended to focus on.
### Steps to Reproduce

1. Go to FAQ page
2. Select any section from the section links
3. Observe the focus of the webpage after the link is clicked

### Expected Behavior 
The correct section is focused and the header does not cover the intended section
### Additional Info
On this screenshot the donate section was clicked and was covered by the website header
![image](https://user-images.githubusercontent.com/30305608/29066699-994cb6f0-7c62-11e7-94f4-f9c9f5c38dce.png)

Branch: f67f58e998004b2402288d094660a7a90acf9a97
dev Build: https://circleci.com/gh/sleepbusorg/sleepbus.org/188

**Comment by leonstafford** [comment]
fixed on dev by 84c7430499ce7917fdc3261939aa14aa9415d6df will deploy to prod along with code for refund policy soon

**Comment by leonstafford** [comment]
recently fixed with another commit
