### ISSUE TITLE
<Prod build> Donations below 1.00 AUD does not show on campaign page

### ISSUE THREAD

**Issue by mop13** [sleepbusorg/sleepbus.org#120]
### Title
Donations below 1.00 AUD does not show on campaign page
### Platform / OS 
Windows 10
### Browser
Chrome
### Description
After making a successful donation, the donations did not reflect on the campaign page
### Steps to Reproduce

1. Select a campaign -- https://www.sleepbus.org/campaign/test-campaign-a
2. Make a donation below 1.00 AUD to the selected campaign
3. After making a successful donation and being redirected to donation success page go back to campaign view

### Expected Behavior 
Successful donations made should reflect on the campaign page.

**Comment by leonstafford** [comment]
@mop13 - let's confirm if it's 0.10 or 0.05 or such required to show as donation, then can re-phrase the bug

**Comment by leonstafford** [comment]
testing showed 0.01 c donation input via DB still showed up on campaign, but didn't contribute to campaign total

![10 cent donation](https://user-images.githubusercontent.com/2066833/30419967-c3205002-996a-11e7-8d51-75fe17b0a32d.png)
![01 cent donation](https://user-images.githubusercontent.com/2066833/30419966-c25d8b3a-996a-11e7-8b4a-159e1eacd93d.png)

**Comment by leonstafford** [comment]
can't replicate with adjusting amount in DB

perhaps due to callback from PayPal or something in that process. low priority for tiny donation amounts. will not fix
