### ISSUE TITLE
[Forgot Password] Layout inconsistent and hides heading

### ISSUE THREAD

**Issue by bakersemail** [sleepbusorg/sleepbus.org#125]
### Title
[Forgot Password] Layout inconsistent and hides heading

### Platform / OS 
Ubuntu 17

### Browser
Chrome

### Description
The forgotten password page result has an inconsistent layout with other pages such as donate. The heading is not centred and is partially hidden by the transparent black hovering box. Need to fix the layout to be consistent and match other pages.

### Steps to Reproduce

 - Either view directly or choose to send forgotten password link.
 - Should see the URL viewing: http://localhost:8080/forgot-password-thanks
 - Heading is not centred and is partially hidden.

### Expected Behavior 
 - Top section should look similar to: http://localhost:8080/donate

**Comment by leonstafford** [comment]
fixed
