### ISSUE TITLE
[Volunteer Database] Hide promotional heading when already signed up

### ISSUE THREAD

**Issue by bakersemail** [sleepbusorg/sleepbus.org#126]
### Title
[Volunteer Database] Hide promotional heading when already signed up

### Platform / OS 
Ubuntu 17

### Browser
Chrome

### Description
Suggestion to hide the promotional heading when already signed up. If the logged in user's email exists in volunteer database, then there should be no need to show the heading unless it is rephrased to onboard others. Though, this issue is not necessary if the promotion is not going to be active for very long.

**Comment by leonstafford** [comment]
won't fix now
