### ISSUE TITLE
Email info@sleepbus.org upon volunteer signup action

### ISSUE THREAD

**Issue by leonstafford** [sleepbusorg/sleepbus.org#128]
Including the volunteer's name and email

**Comment by bakersemail** [comment]
Is there a preferred structure or wording to the subject and body? Should we be keeping in mind potential automation which might intepret these emails?

**Comment by leonstafford** [comment]
@bakersemail - would re-use template that the "A new user has just joined sleepbus" one uses, the mailer code will be evident from that, too. 

No need to consider automation/parsing of these, though current structure is not that hard to.

`fname, email1` are the fields required.

**Comment by leonstafford** [comment]
fixed
