### ISSUE TITLE
Currency not formatted correctly everywhere

### ISSUE THREAD

**Issue by leonstafford** [sleepbusorg/sleepbus.org#28]
### Background

sleepbus is currently active in the Australian market, which prefers the format $1,234.56 for its currency.

Currently, at least one area of the site is not displaying currency values correctly:

 - campaign page: if a user donates $1,000.05, it shows as $1,000.05

We want to ensure that all area in the website and emails are showing currency in the correct format.

This could be in the form of a Currency class used in place of numbers or just a filter in the template to transform the numbers appropriately.

Tip for finding references - find the columns in database tables which are used to store monetary values. Find references to these and ensure formatting is being carried out.

### Acceptance criteria

- [ ]  All occurrances of monetary values take the form of $1,000,000.00 or in the case of negative, -$1,000,000

**Comment by bakersemail** [comment]
Hi Leon,

Isn't this already correct? "campaign page: if a user donates $1,000.05, it shows as $1,000.05"

**Comment by leonstafford** [comment]
Ah, think you've caught me again! I was doing manual donation for a bank transfer that came in yesterday and input as a number. I'll check if the others are being stored as chars, may be another story there.

**Comment by bakersemail** [comment]
@leonstafford Can this be closed?
