### ISSUE TITLE
move to AWS hosting

### ISSUE THREAD

**Issue by leonstafford** [sleepbusorg/sleepbus.org#29]
### Background

Currently, hosted on a Bluehost VPS, which is terribly lacking in flexibility and unlikely to stand up to increased load expected in coming weeks.

Not letting perfect get in the way of good, this story is for getting some infrastructure as code to allow quick and idempotent provisioning of multiple environments (test, uat, prod). 

A future story may see further optimisation, such as using ECS with auto scaling. 

### Acceptance criteria

 - [x] Route53 to take over DNS management
 - [x] Terraform scripts to spin up an environment with web + sql
 - [x] Ansible playbook to configure web instance
   - [SSL per instance] 
 - [x] DEV site deploying from `dev` branch
 - [x] UAT site deploying from `uat` branch  
 - [x] PROD site up and running on AWS, deployed from tags based on master (just deployed from master)

### Testing

 - [x] Tested migration strategy from current production site to new UAT

**Comment by bakersemail** [comment]
Do you have an account yet?

**Comment by leonstafford** [comment]
No, didn't get much response from Amazon's non-profit/government arm, so may setup new account today.

**Comment by TheHollidayInn** [comment]
Any thoughts on using Docker for creating the deploy?

**Comment by leonstafford** [comment]
Hi @TheHollidayInn - thanks for joining in! I have some experience with Docker/ECS and think that's likely to happen after immediate needs are met.
