### ISSUE TITLE
Volunteer sign-up form, just like the newsletter

### ISSUE THREAD

**Issue by leonstafford** [sleepbusorg/sleepbus.org#37]
### Background

Need quick way to capture volunteer information. Re-using system in place for newsletter signups may be quick win.

### Acceptance criteria

- [x] at `/volunteer` path
- [x] thank you page text to be 
- [x] linked to from volunteer signup banner 

>You're Awesome!
>
>Thank you for your support. We will be in touch shortly with more details.

- [x] thank you page, as per design below

![volunteer_thank_you_page_v2](https://user-images.githubusercontent.com/2066833/27561921-3eef1bcc-5b1e-11e7-8683-1c23fb705604.jpg)

 - [x] fields for volunteer signup, simply Name and Email, along with text and social links as below
![volunteersignup](https://user-images.githubusercontent.com/2066833/27525890-bb4a5080-5a95-11e7-9d67-a177582d9ebe.jpg)

**Comment by leonstafford** [comment]
`CREATE TABLE volunteers SELECT * FROM newsletters_subscribers LIMIT 0;`

`CREATE TABLE volunteers_groups SELECT * FROM newsletter_subscribers_groups LIMIT 0;`

**Comment by leonstafford** [comment]
deployed WIP to `dev` for feedback

**Comment by leonstafford** [comment]
@mop13 this one is finally live, if you could please do another test on production before closing off

**Comment by leonstafford** [comment]
@mop13 FYI, checked that a signed up name + email were recorded in db.

**Comment by mop13** [comment]
@leonstafford I've successfully signed up in the volunteers page so how do I check if it was recorded in db?

**Comment by leonstafford** [comment]
```
     title: NULL
           fname: TEST_aldrich
           mname: NULL
           lname: NULL
             dob: NULL
          email1: aldrichsiojo@gmail.com
          email2: NULL
```

all good

**Comment by leonstafford** [comment]
@mop13 will get you more access soon for verification, closing this one for now
