### ISSUE TITLE
Cannot run locally anymore

### ISSUE THREAD

**Issue by bakersemail** [sleepbusorg/sleepbus.org#49]
Hi Sleepbus team,

I'm having issues following the local instructions for a local build. I have reinstalled docker and still get this issue after a fresh checkout of the project. This is what happens when I visit the homepage localhost:8080 once its running in docker.

```
Warning: include_once(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /var/www/html/index.php on line 58

Warning: include_once(./application/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/index.php on line 58

Warning: include_once(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /var/www/html/index.php on line 58

Warning: include_once(): Failed opening './application/vendor/autoload.php' for inclusion (include_path='.:/usr/local/lib/php') in /var/www/html/index.php on line 58

Warning: main(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /var/www/html/index.php on line 60

Fatal error: Class 'Dotenv\Dotenv' not found in /var/www/html/index.php on line 60
```

**Comment by leonstafford** [comment]
@bakersemail - sorry, may have been a few changes in there, mine runs fine with the `destroy_rebuild` script, so I think it may be due to adding Composer, would explain the missing vendor folder and dotenv lib. Let me check what the command should be...

**Comment by leonstafford** [comment]
With composer installed, will need to

`php composer.phar install`

passing in argument for target dir, which is 

`/src/application`

**Comment by leonstafford** [comment]
`php composer.phar install composer install -d /src/application` should do it. 

I've just been a bit busy travelling and trying to get some quick fixes in, so have been a bit sloppy with the local dev env.

**Comment by leonstafford** [comment]
`php composer.phar install composer install -d /src/application` should do it. 

I've just been a bit busy travelling and trying to get some quick fixes in, so have been a bit sloppy with the local dev env.

**Comment by bakersemail** [comment]
Can this be included into the destroy_rebuild script?

**Comment by leonstafford** [comment]
@bakersemail, haven't forgotten about this, just on some really crappy internet for next 2 days, so can't easily rebuild without cache. Aiming to get this sorted over next week.

**Comment by bakersemail** [comment]
Cheers. Will be glad to see it fixed so I can help out where I can again.

**Comment by leonstafford** [comment]
@bakersemail - have just pushed a fix to master that sorted this out on a new env for me, let me know if any issues

**Comment by leonstafford** [comment]
@bakersemail - just added another commit which should retain the vendor files after the watch job syncs app folder again. missed that!
