### ISSUE TITLE
Thanks messages from templates, not db

### ISSUE THREAD

**Issue by leonstafford** [sleepbusorg/sleepbus.org#53]
Migrate following:

 - [x] Connect
 - [x] Speaker request
 - [x] enewsletter signup
 - [x] forgot password
 - [x] reset password
 - [x] birthday pledge - this is one of those pink flash messages....
 - [x] create campaign - pink message
 - [x] posting a comment for a campaign by a user - already in code
 - [x] update profile - already in code
 - [x] one time donation
 - [x] recurring donation
 - [x] donation cancel page
 - [x] donation unsuccessful page

**Comment by leonstafford** [comment]
@mop13 please file new bug if doesn't exist yet - campaign donation thanks message is using one time donation thanks message

**Comment by leonstafford** [comment]
@mop13 - created one here https://github.com/sleepbusorg/sleepbus.org/issues/114

**Comment by mop13** [comment]
@leonstafford how do I trigger recurring donation and donation unsuccessful page? what does it look like?

**Comment by leonstafford** [comment]
@mop13 sorry for delay https://www.sleepbus.org/donation/unsuccess

The monthly/recurring URL I think is https://www.sleepbus.org/recurring/order-confirm , which is erroring and likely related to the existing issue we have documented.

We can ignore that for this issue and close this if the others are fine as this is already on prod. Have seen the https://github.com/sleepbusorg/sleepbus.org/issues/116 issue and will prioritize that, too

**Comment by mop13** [comment]
Verified working in latest prod build
