### ISSUE TITLE
 Bottom half of the Pledge button is not clickable

### ISSUE THREAD

**Issue by mop13** [sleepbusorg/sleepbus.org#54]
**Title**: Bottom half of the Pledge button is not clickable.

**Platform / OS:** Windows Desktop
**Browser:** Google Chrome

**Description:** The Pledge button is not clickable when user hovers then click/tap on the bottom half of the button.

**Steps to Reproduce:**

1. Go to about us link of the page -- https://www.sleepbus.org/about-us
2. Scroll down until you see the pledge button in the middle
3. Hover on the bottom half then try to click on the button. Notice that the bottom part is not clickable.

**Expected Behavior:** All parts of the button are clickable.

**Additional Info:** This only happens on the “about us” section but works fine on other pages wherein the pledge button is scene. There is also a noticeable “---“ extra characters after the word pledge.

**Comment by mop13** [comment]
The problem is also present in the donate and fundraise button.
The extra character "--" is also present on this page: 
https://dev.sleepbus.org/connect

**Comment by mop13** [comment]
still not clickable the bottom half of the donate, pledge and fundraise button in https://www.sleepbus.org/about-us
![image](https://user-images.githubusercontent.com/30305608/28960354-e04e7f46-7930-11e7-95fe-e381449db5e6.png)

**Comment by leonstafford** [comment]
@mop13 my bad, thought it was due to other common issue. Have pushed a new fix up now, should be sorted on prod.

**Comment by mop13** [comment]
@leonstafford one last thing "Pledge--" is still present in https://www.sleepbus.org/donate

**Comment by leonstafford** [comment]
copy that. will put back in dev column, need to find where that content is coming from... the theme of today's work 🔎

**Comment by mop13** [comment]
Verified fixed in prod build
