### ISSUE TITLE
[Forgot Password] Spelling mistake occurs for "Retype password" field.

### ISSUE THREAD

**Issue by mop13** [sleepbusorg/sleepbus.org#56]
### Title
[Forgot Password] Spelling mistake occurs for "Retype password" field.

### Platform / OS 
Windows, Mac
### Browser
Firefox (45.0, 47.0), Chrome (51.0, 53.0), IE (10, 11), Safari 10

### Description
Spelling mistake on placeholder text of "Retype password" field.

### Steps to Reproduce

 1. Open Url.
2. Click on "Forgot password" link.
3. Observe the "Retype password" field placeholder text.

### Expected Behavior 
"Reype password" placeholder text should be like, "Retype password".

### Additional Info
Branch: 0b650b07369f1e40f3df170a90fc2b82e13df2d4
dev Build: https://circleci.com/gh/sleepbusorg/sleepbus.org/125

**Comment by thekaruna** [comment]
@mop13 it should be fixed now . Please have a look.

**Comment by mop13** [comment]
Verified Fixed.
Branch: 93ddeb55e439de3853f9c31eb1c707378bc648aa
dev Build: https://circleci.com/gh/sleepbusorg/sleepbus.org/145

**Comment by mop13** [comment]
verified fixed on prod build
