### ISSUE TITLE
The favicon isn't displayed on the main page after opening the site

### ISSUE THREAD

**Issue by mop13** [sleepbusorg/sleepbus.org#60]
### Title
The favicon isn't displayed on the main page after opening the site
### Platform / OS 
Windows 10
### Browser
Mozilla Firefox 54.0 (64-bit)
### Description
The favicon isn't displayed on the main page after opening the site
### Steps to Reproduce

1. Open the site https://www.sleepbus.org/
2. Pay attention to the top of the page

### Expected Behavior 
The favicon is displayed on the main page after opening the site 
### Additional Info
Branch: 0b650b07369f1e40f3df170a90fc2b82e13df2d4
dev Build: https://circleci.com/gh/sleepbusorg/sleepbus.org/125

**Comment by leonstafford** [comment]
@thekaruna please create favicon of the sleepbus light blue with bus icon, available from previous PDF or media downloads page in website

Use modern conventions for favicon, ie support high dpi devices

**Comment by thekaruna** [comment]
@leonstafford  okay i have included a seperate folder for favicons inside images folder that includes all HD favicons for web + mobile devices and apps .

@mop13 please have a look.

**Comment by mop13** [comment]
Verified Fixed on
Branch: c6dd5bdcb8e9b8a8e630a5400a2bdc0200b8de1b
dev Build: https://circleci.com/gh/sleepbusorg/sleepbus.org/165

**Comment by mop13** [comment]
verified fixed in prod build
