### ISSUE TITLE
[Blog] Image disappears by mouse hovering  on it

### ISSUE THREAD

**Issue by mop13** [sleepbusorg/sleepbus.org#63]
### Title
[Blog] Image disappears by mouse hovering  on it
### Platform / OS 
Windows 10
### Browser
Google Chrome
### Description
[Blog] Image disappears by mouse hovering  on it
### Steps to Reproduce

1.	Navigate to the https://dev.sleepbus.org/blog
2.	Place the mouse cursor on the image or on any of displayed links on it

### Expected Behavior 
Image should not disappear
### Additional Info
Branch: 0b650b07369f1e40f3df170a90fc2b82e13df2d4
dev Build: https://circleci.com/gh/sleepbusorg/sleepbus.org/125

**Comment by leonstafford** [comment]
by design
