### ISSUE TITLE
Button "Back To Top" shows only on FAQ page

### ISSUE THREAD

**Issue by mop13** [sleepbusorg/sleepbus.org#65]
### Title
Button "Back To Top" shows only on FAQ page
### Platform / OS 
Windows
### Browser
Google Chrome
### Description
"Back To Top" button missing on all pages except in FAQ page
### Steps to Reproduce

1. Go to the main page https://dev.sleepbus.org and scroll down. You should not see the "Back to Top" button
2. Go to the page FAQ page https://dev.sleepbus.org/faq and scroll down. You will see the "Back to Top" button in right

### Expected Behavior 
Back To Top should be present whenever a page can be scrolled down and top of the page is no longer shown.
### Additional Info
Branch: 0b650b07369f1e40f3df170a90fc2b82e13df2d4
dev Build: https://circleci.com/gh/sleepbusorg/sleepbus.org/125

**Comment by leonstafford** [comment]
won't fix
