### ISSUE TITLE
[Campaign]  Updating a campaign, does not update the amount.

### ISSUE THREAD

**Issue by mop13** [sleepbusorg/sleepbus.org#66]
### Title
[Campaign]  Updating a campaign, does not update the amount.
### Platform / OS 
Windows 10
### Browser
Google Chrome
### Description
Campaign amount is not updated with the correct amount. It still reflects the initial
amount the user inputted during the first edit.
### Steps to Reproduce

1. Login to the application https://dev.sleepbus.org
2. Click on ‘Fundraiser’ button on the header.
3. Enter the details for campaign name as ‘Sleep peacefully’, Campaign goal as ‘0’, campaign end date as ’15-10-2017, I am fundraising as ‘Campaign as a specific town’ and choose a photo.
4. Click on ‘Create Campaign’ button.
5. Click on Edit Campaign'.
6. Update the campaign goal to ‘100 AUD’ and click on ‘Update Campaign’

### Expected Behavior 
Amount should be updated to 100 AUD
### Additional Info
Branch: 0b650b07369f1e40f3df170a90fc2b82e13df2d4
dev Build: https://circleci.com/gh/sleepbusorg/sleepbus.org/125

**Comment by leonstafford** [comment]
@mop13 could you please add before/after screenshots to this one? Want to be sure it's the campaign goal which is not updating vs just the campaign amount, which won't update until donations are made..

**Comment by mop13** [comment]
@leonstafford after reviewing the issue I think the reporter mistakenly points the campaign amount to the campaign goal. so you we can close this issue already.
