### ISSUE TITLE
[About us] Incorrect amount information is shown after switching to another page

### ISSUE THREAD

**Issue by mop13** [sleepbusorg/sleepbus.org#71]
### Title
[About us] Incorrect amount information is shown after switching to another page
### Platform / OS 
Windows
### Browser
Chrome
### Description
[About us] Incorrect amount information is shown after switching to another page
### Steps to Reproduce

1. Open First Page (Home page) > 
2. click page "About us"  > Here's what we're about >
3. Scroll down and look for donate button in "three ways you can get involved" section.
4. Notice the info 27.5$ for 1 good night's sleep
5. Click on the donate button and get directed to a new page that shows 55$ for 1 safe sleep

### Expected Behavior 
Information about default amounts of donation should be consistent throughout all pages (whether its 55 or 27.5)
### Additional Info
Branch: 0b650b07369f1e40f3df170a90fc2b82e13df2d4
dev Build: https://circleci.com/gh/sleepbusorg/sleepbus.org/125

**Comment by mop13** [comment]
The 27.5 value for 1 day sleep is also present on this page -- https://dev.sleepbus.org/volunteer-signup-thanks

**Comment by leonstafford** [comment]
@mop13 confirmed 1 night is 27.50 - but default text is desired to be 2 nights' worth @ $55. 

So `One safe sleep is just $55.00` is definitely a bug, but placeholder texts aren't necessarily. Could you please confirm all places needing clarification in this issue's acceptance criteria as a checklist? will make it easier to do as one task

**Comment by mop13** [comment]
Im closing this ticket and putting the inconsistent text/pricing checklist on this ticket #89
