### ISSUE TITLE
[Signup] Overlapping text in password text field

### ISSUE THREAD

**Issue by mop13** [sleepbusorg/sleepbus.org#72]
### Title
[Signup] Overlapping text in password text field
### Platform / OS 
Windows 10
### Browser
IE 11 and Microsoft Edge
### Description
An icon overlaps with the "hide/show" text in password field
### Steps to Reproduce

1. Go to Signin page -- https://dev.sleepbus.org/signin
2. Type any password and click show
3. click on email text field
4. click on password text field. Notice the x icon overlapping with "hide/show" text

### Expected Behavior 
No overlapping icon or text
### Additional Info
Not happening on Chrome and Firefox

Branch: 0b650b07369f1e40f3df170a90fc2b82e13df2d4
dev Build: https://circleci.com/gh/sleepbusorg/sleepbus.org/125

![image](https://user-images.githubusercontent.com/30305608/28406650-fd9927c8-6d63-11e7-8795-ec1214c188d2.png)

**Comment by thekaruna** [comment]
@mop13 . This one is also fixed . Please have a look.

**Comment by mop13** [comment]
Verified Fixed on
Branch: c6dd5bdcb8e9b8a8e630a5400a2bdc0200b8de1b
dev Build: https://circleci.com/gh/sleepbusorg/sleepbus.org/165

**Comment by mop13** [comment]
verified fixed in prod build
