### ISSUE TITLE
No confirmation email is sent to the user when the user subscribes to sleepbus newsletter or volunteer list

### ISSUE THREAD

**Issue by mop13** [sleepbusorg/sleepbus.org#76]
### Title
No confirmation email is sent to the user when the user subscribes to sleepbus.
### Platform / OS 
Windows 10
### Browser
Chrome
### Description
No confirmation email is sent to the user when the user subscribes to sleepbus.
### Steps to Reproduce

1. Enter the url- https://dev.sleepbus.org/
2. Click on "Get our Awesome emails" option present at the bottom of the application.
3. Enter all the necessary details in the given fields.
4. Click on Join button.
5. Open the mentioned email.
6. Observe whether user received any email or not.

### Expected Behavior 
A confirmation email should be sent to the user when he/she subscribe to sleepbus.
### Additional Info
Branch: 0b650b07369f1e40f3df170a90fc2b82e13df2d4
dev Build: https://circleci.com/gh/sleepbusorg/sleepbus.org/125

**Comment by leonstafford** [comment]
won't fix
