### ISSUE TITLE
[Profile] User is able to update the old password as the new password.

### ISSUE THREAD

**Issue by mop13** [sleepbusorg/sleepbus.org#77]
### Title
[Profile] User is able to update the old password as the new password.
### Platform / OS 
Windows 10
### Browser
Chrome
### Description
User is able to update the old password as the new password.
### Steps to Reproduce

1. Login the application.
2. Click on "Profile settings" option present under "My Account" section.
3. Enter the current password in the Current Password field.
4. Enter the same password in the New password and in "Password Confirmation" field.
5. Click on "Update Profile" button.
6. Observe the behavior.

### Expected Behavior 
User should not be able to update the old password as new password. A validation message "New password should be different from old password." should be displayed.
### Additional Info
Branch: 0b650b07369f1e40f3df170a90fc2b82e13df2d4
dev Build: https://circleci.com/gh/sleepbusorg/sleepbus.org/125

**Comment by leonstafford** [comment]
@bakersemail could you please take a look at this one? have had some strange reports that sound like sessions are not being destroyed properly or other weird auth behaviour

**Comment by bakersemail** [comment]
@leonstafford Did this issue start after the updates to password storage to bcrypt that I did before?

**Comment by leonstafford** [comment]
@bakersemail - possibly, but no way to tell. We weren't testing much then and didn't have any report of it before.

**Comment by bakersemail** [comment]
@leonstafford Is there steps to reproduce the session issues you mention? This issue is just about not allowing users to set the same password as their current and from looking at the code, this feature never appeared to exist for it to be considered a bug that it's missing. Is this a feature request instead?

**Comment by leonstafford** [comment]
@bakersemail - sorry, wrong issue - we were having another issue with being able to signin with any random password, Try on www site with an email you've used to sign up. Log out and then login using any random password that is not your actual one.

**Comment by bakersemail** [comment]
@leonstafford I have a feeling that's due to how the session data is managed. I'll have a look into that too. Will need a new issue logged for it though I think, otherwise this one is going to get awful confusing.

**Comment by bakersemail** [comment]
@leonstafford Fixed that auth issue. Sent a pull request. Made a really silly mistake in the last fixes.

**Comment by bakersemail** [comment]
@leonstafford Pull request created for the new/current password comparison.

**Comment by leonstafford** [comment]
@bakersemail - thanks! No worries, will get the auto-testing running on build soon and we now have @mop13 doing manual QA on issues as they pass through the dev board, so in a better place 😸
