### ISSUE TITLE
The default amount written on the textfield of 1 year safe sleep is different from the description 

### ISSUE THREAD

**Issue by mop13** [sleepbusorg/sleepbus.org#80]
### Title
The default amount written on the textfield of 1 year safe sleep is different from the description 
### Platform / OS 
Windows 10
### Browser
Chrome
### Description
The default amount written on the textfield of 1 year safe sleep is 20,075.00 while on the description it says 10,037.50
### Steps to Reproduce

1. Go to 1 year safe sleep page -- https://www.sleepbus.org/one-year-safe-sleep
2. Check the amount written on the description versus the default amount on the text field

### Expected Behavior 
Consistent amount should be shown whether it's 10k or 20k
### Additional Info
Branch: 3df28384163f3c9dc262b86f61139745073d1332
dev Build: https://circleci.com/gh/sleepbusorg/sleepbus.org/128

**Comment by mop13** [comment]
Related to this issue: https://github.com/sleepbusorg/sleepbus.org/issues/71
- what is the default amount for 1 safe sleep 55 or 27.5? from there computation can be made for monthly and yearly default

**Comment by leonstafford** [comment]
getting confirmation from Simon

**Comment by leonstafford** [comment]
dup https://github.com/sleepbusorg/sleepbus.org/issues/89
