### ISSUE TITLE
[Pledge] Pledge now button gets overlap by UI arrow

### ISSUE THREAD

**Issue by mop13** [sleepbusorg/sleepbus.org#81]
### Title
[Pledge] Pledge now button gets overlap by UI arrow
### Platform / OS 
Windows 10
### Browser
Chrome
### Description
Pledge now button gets overlap by UI arrow
### Steps to Reproduce

1. Go to pledge screen (donate menu > pledge) -- https://dev.sleepbus.org/pledge
2. Enter valid name name and birthdate
3. Enter Invalid email then click pledge now button
4. Notice that after the error message appeared the UI gets move down and overlapping occurs

### Expected Behavior 
No overlapping should occur between UI elements.
### Additional Info
Half of the Pledge now button will also be not clickable as a result of this overlapping issue

![image](https://user-images.githubusercontent.com/30305608/28448901-4c71f4f6-6e0e-11e7-82a6-cb2b872d3fab.png)

Branch: 3df28384163f3c9dc262b86f61139745073d1332
dev Build: https://circleci.com/gh/sleepbusorg/sleepbus.org/128

**Comment by thekaruna** [comment]
@mop13 should be fixed , please have a look.

**Comment by mop13** [comment]
Verified fixed on
Branch: 54789c348427efcfa22edd86964eb9b398ea178e
dev Build: https://circleci.com/gh/sleepbusorg/sleepbus.org/169

**Comment by mop13** [comment]
verified fixed on prod build
