### ISSUE TITLE
Suggestion: Pages that require inputting dates should have a calendar attached for better validation

### ISSUE THREAD

**Issue by mop13** [sleepbusorg/sleepbus.org#82]
### Title
Pages that require inputting dates should have a calendar attached for better validation
### Platform / OS 
Windows 10
### Browser
Chrome
### Description
In campaign and pledge screen wherein user is required to input dates a better option would be to put a calendar once the user selects on the date field to better secure input validation.
### Steps to Reproduce

1. Go to Pledge or Campaign page
2. Check on the date input method

### Expected Behavior 
This is more of a suggestion but it's common practice in date input to attach a calendar

**Comment by leonstafford** [comment]
won't fix
