### ISSUE TITLE
[Blog] FB Share it button has an extra "--" character

### ISSUE THREAD

**Issue by mop13** [sleepbusorg/sleepbus.org#83]
### Title
[Blog] FB Share it button has an extra "--" character
### Platform / OS 
Windows 10
### Browser
Chrome
### Description
[Blog] FB Share it button has an extra "--" character
### Steps to Reproduce

1. Launch blog page (from footer links select blog > an update) -- https://dev.sleepbus.org/blog/category/blog2
2. Scroll down towards the bottom of the blog
3. Notice the Facebook Share it button has an extra character

### Expected Behavior 
Remove "--" at the end of the share it button
### Additional Info
![image](https://user-images.githubusercontent.com/30305608/28449902-638ff090-6e16-11e7-9556-450ab6bea6fa.png)

Branch: 3df28384163f3c9dc262b86f61139745073d1332
dev Build: https://circleci.com/gh/sleepbusorg/sleepbus.org/128

**Comment by leonstafford** [comment]
@mop13 this one can be tested on dev now. thx

**Comment by mop13** [comment]
Verified Fixed
Branch: 93ddeb55e439de3853f9c31eb1c707378bc648aa
dev Build: https://circleci.com/gh/sleepbusorg/sleepbus.org/145

**Comment by mop13** [comment]
Verified fixed on prod build
