### ISSUE TITLE
[my donations] Disorganize side menu layout when browser is resize

### ISSUE THREAD

**Issue by mop13** [sleepbusorg/sleepbus.org#86]
### Title
[my donations] Disorganize side menu layout when browser is resize
### Platform / OS 
Windows 10
### Browser
Chrome
### Description
The logout link position in side menu moves improperly causing a disorganize side menu links. see attached image for reference.
### Steps to Reproduce

1. Go to My donations page (my account > my donations) -- https://dev.sleepbus.org/user/profile
2. Resize browser and observe the position movement of the logout link. 

### Expected Behavior 
Link positions should remain organize even if the browser is resize
### Additional Info
![image](https://user-images.githubusercontent.com/30305608/28461563-bb4de034-6e49-11e7-9baf-4095926c204f.png)

Branch: 3df28384163f3c9dc262b86f61139745073d1332
dev Build: https://circleci.com/gh/sleepbusorg/sleepbus.org/128

**Comment by leonstafford** [comment]
wont fix current mobile/responsive issues
