### ISSUE TITLE
Disorganize Top menu layout when browser is resize

### ISSUE THREAD

**Issue by mop13** [sleepbusorg/sleepbus.org#87]
### Title
Disorganize Top menu layout when browser is resize
### Platform / OS 
Windows 10
### Browser
Chrome
### Description
The links on the header gets misaligned after resizing the browser
### Steps to Reproduce

1. Launch Home page -- https://dev.sleepbus.org/
2. Resize the browser until the top menu positions move

### Expected Behavior 
Top Menu positions should remain organize even when browser is resize
### Additional Info
![image](https://user-images.githubusercontent.com/30305608/28462040-006e98aa-6e4c-11e7-8620-13922a4adfea.png)

Branch: 3df28384163f3c9dc262b86f61139745073d1332
dev Build: https://circleci.com/gh/sleepbusorg/sleepbus.org/128

**Comment by leonstafford** [comment]
wont fix current mobile/responsive issues
