### ISSUE TITLE
[Volunteer] Disorganize layout when browser is resize

### ISSUE THREAD

**Issue by mop13** [sleepbusorg/sleepbus.org#88]
### Title
[Volunteer] Disorganize layout when browser is resize
### Platform / OS 
Windows 10
### Browser
Chrome
### Description
The UI including images, text and buttons overlap when the browser is resize. See attached images for reference.
### Steps to Reproduce

1. Go to Volunteer Page
2. Enter valid details then click on join and you will be directed to volunteer thank you page -- https://dev.sleepbus.org/volunteer-signup-thanks
3. Resize the browser until the UI positions begins to move.
4. Observe the buttons, images and text in the page

### Expected Behavior 
UI elements are still organized even when the browser is resize
### Additional Info
![image](https://user-images.githubusercontent.com/30305608/28462822-99649782-6e4f-11e7-9aa5-3353c5df35a9.png)

![image](https://user-images.githubusercontent.com/30305608/28462806-84911718-6e4f-11e7-8c3f-a9c5d6dd28ab.png)

Branch: 3df28384163f3c9dc262b86f61139745073d1332
dev Build: https://circleci.com/gh/sleepbusorg/sleepbus.org/128

**Comment by leonstafford** [comment]
wont fix current mobile issues
