### ISSUE TITLE
[FAQ] text error in FAQ page

### ISSUE THREAD

**Issue by mop13** [sleepbusorg/sleepbus.org#91]
### Title
[FAQ] text error in FAQ page
### Platform / OS 
Windows 10
### Browser
Chrome
### Description
Inappropriate used of "..." in the the sentence construction found in the paragraph answering the question "How do I organise a sleepbus in my local area?"
### Steps to Reproduce

1. Open FAQ page of the website -- https://dev.sleepbus.org/faq#faq-donate
2. Look for the "How do I organise a sleepbus in my local area?" question and press expand button (+)

### Expected Behavior 
The Inappropriate "..." characters is removed
### Additional Info
![image](https://user-images.githubusercontent.com/30305608/28506927-6fcafeb6-7061-11e7-8b9e-6d1c6de46141.png)

Branch: 3df28384163f3c9dc262b86f61139745073d1332
dev Build: https://circleci.com/gh/sleepbusorg/sleepbus.org/128

**Comment by mop13** [comment]
verified fixed on dev build
Branch: 3f0eb2998058550b7d94af8cb14ebf200107b234
dev Build: https://circleci.com/gh/sleepbusorg/sleepbus.org/150

**Comment by leonstafford** [comment]
@mop13 - this should now be on prod. After verifying prod stories and closing them, can you please remove them from the GH Project board to keep cards there to a minimum. We can still see audit trail of them in the GH Issues section if needed. Cheers

**Comment by mop13** [comment]
verified fixed in prod build
