### ISSUE TITLE
[Blog] Image link is not clickable

### ISSUE THREAD

**Issue by mop13** [sleepbusorg/sleepbus.org#93]
### Title
[Blog] Image link is not clickable
### Platform / OS 
Windows 10
### Browser
Microsoft Edge / IE
### Description
The large portion of the image link is not clickable. There is only a small spot at the bottom that can be click that will direct user towards the article page.
### Steps to Reproduce

1. Launch website using Microsoft Edge / IE as the browser
2. Go to Blog page and try clicking on the image

### Expected Behavior 
User will be directed towards the article page if image is clicked
### Additional Info
Only the marked section is clickable
![image](https://user-images.githubusercontent.com/30305608/28510591-dae9127c-707b-11e7-97a5-05c4a6960b84.png)

**Comment by leonstafford** [comment]
@mop13 have fixed the other little blog issue (https://github.com/sleepbusorg/sleepbus.org/issues/83) as I'm doing this related task  (https://github.com/sleepbusorg/sleepbus.org/issues/94)

Regarding this issue with Edge/Win10, could you please do some debugging and see if you can fashion a fix by inspecting/editing HTML within Edge? I unfamiliar with dev tools available on Edge and I won't have access to a convenient Win10/Edge VM for at least a few days. 

My guess is malformed HTML...

**Comment by leonstafford** [comment]
@thekaruna - do you have an Edge instance handy to test? We do have a Browserstack account free for a year for non-profits/open source, which I'll share with you guys, too...

**Comment by leonstafford** [comment]
won't fix. low traffic to these pages, other link generally clickable. redesign imminent
