### ISSUE TITLE
add new newsletter under blog section

### ISSUE THREAD

**Issue by leonstafford** [sleepbusorg/sleepbus.org#94]
issue created for tracking work

remaining tasks before complete:

- [x] link to newsletter post from old blog's sidebar
- [x] all links in newsletter to right places
- [x] image and text for the link to newsletter from blog listing page - what should these be???
- [x] re-enable volunteer signup banner
- [x] Google Tag Manager code on new blog page
- [x] page title on new blog page

**Comment by leonstafford** [comment]
merged into dev, but still a WIP, aiming to finalize and go live tomorrow

**Comment by leonstafford** [comment]
@mop13 - not many details for you for this story, sorry, but if you can take a look at /blog on the dev site and see if anything major, broken links, etc. I'm awaiting confirmation on which image to use to link to the july 2k17 newsletter

**Comment by mop13** [comment]
Verified all links are working in dev and prod build

**Comment by leonstafford** [comment]
this one already all on prod, so will close off
