### ISSUE TITLE
[Blog] Error page displayed after clicking "donate campaign" link

### ISSUE THREAD

**Issue by mop13** [sleepbusorg/sleepbus.org#96]
### Title
[Blog] Error page displayed after clicking "donate campaign" link
### Platform / OS 
Windows 10
### Browser
Chrome
### Description
An error message appeared on top of the page after clicking on the "donate to lincoln's campain" link
### Steps to Reproduce

1. Go to blog section of the page
2. Click on 1st blog image (whats been happening) -- https://dev.sleepbus.org/blog/july_2017_news
3. Look for the "donate to lincoln's campain" link and click on it.

### Expected Behavior 
User will  be directed to an error page
### Additional Info
![image](https://user-images.githubusercontent.com/30305608/28560562-c5d936dc-714d-11e7-9903-2e0b8db8a789.png)

Branch: 93ddeb55e439de3853f9c31eb1c707378bc648aa
dev Build: https://circleci.com/gh/sleepbusorg/sleepbus.org/145

**Comment by leonstafford** [comment]
this one will be OK on prod https://www.sleepbus.org/campaign/lincolnbarclayscampaign, we just don't have that in dev. 

maybe change the issue to a "Campaign not found error" lacking?

**Comment by mop13** [comment]
I've created a new issue so this can be closed as invalid or duplicate
